name: citycatpg

channels:
  - conda-forge

dependencies:
  - geopandas=0.7.0
  - rasterio=1.1.4
  - netCDF4=1.5.3
  - psycopg2=2.8.5
  - sqlalchemy=1.3.17
  - pika=1.1.0
  - pip:
      - citycatio==0.3.4