name: tests
on: [push]


jobs:
  conda:
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
      rabbit:
        image: rabbitmq
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Set up conda
        uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.8
          activate-environment: citycatpg
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: run tests
        run:  |
          pip install coverage
          coverage run -m unittest discover
          coverage xml
        shell: bash -l {0}

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
